# PL_TARGET_DENSITY - You can increase this if Global Placement fails with error GPL-0302.
# Users have reported that values up to 0.8 worked well for them.
set ::env(PL_TARGET_DENSITY) 0.8

# CLOCK_PERIOD - Increase this in case you are getting setup time violations.
# The value is in nanoseconds, so 10ns == 100MHz.
set ::env(CLOCK_PERIOD) "1000"

# Hold slack margin - Increase them in case you are getting hold violations.
set ::env(PL_RESIZER_HOLD_SLACK_MARGIN) 0.1
set ::env(GLB_RESIZER_HOLD_SLACK_MARGIN) 0.05

# RUN_LINTER, LINTER_INCLUDE_PDK_MODELS - Disabling the linter is not recommended!
set ::env(RUN_LINTER) 1
set ::env(LINTER_INCLUDE_PDK_MODELS) 1

# Configuration docs: https://openlane.readthedocs.io/en/latest/reference/configuration.html

# Load configuration auto-generated by tt-support-tools
set script_dir [file dirname [file normalize [info script]]]
set ::env(DESIGN_NAME) ip_line_mux
set ::env(VERILOG_FILES) "$::env(DESIGN_DIR)/../../verilog/rtl/ip_line_mux.v"

set ::env(FP_PIN_ORDER_CFG) "$::env(DESIGN_DIR)/pin_order.cfg"


# Save some time
set ::env(RUN_KLAYOUT_XOR) 0
set ::env(RUN_KLAYOUT_DRC) 0

# Don't put clock buffers on the outputs
set ::env(PL_RESIZER_BUFFER_OUTPUT_PORTS) 0

# Allow use of specific sky130 cells
set ::env(SYNTH_READ_BLACKBOX_LIB) 1

# Reduce wasted space
#set ::env(FP_CORE_MARGIN) 1

set ::env(TOP_MARGIN_MULT) 1
set ::env(BOTTOM_MARGIN_MULT) 1
set ::env(LEFT_MARGIN_MULT) 6
set ::env(RIGHT_MARGIN_MULT) 6

# Die size
set ::env(FP_SIZING) absolute
set ::env(DIE_AREA) "0 0 100 25"

set ::env(PL_BASIC_PLACEMENT) {0}
set ::env(GRT_ALLOW_CONGESTION) "1"

set ::env(FP_IO_HLENGTH) 1
set ::env(FP_IO_VLENGTH) 1

# Clock
set ::env(RUN_CTS) 1
set ::env(CLOCK_PORT) {clk}

# Don't use power rings or met5 layer
set ::env(DESIGN_IS_CORE) 0
set ::env(RT_MAX_LAYER) {Metal4}