DESIGN_NAME: ip_row_mux
VERILOG_FILES: dir::../../verilog/rtl/ip_row_mux/ip_row_mux.v
IO_PIN_ORDER_CFG: dir::pin_order.cfg

VDD_NETS:
- VDD
GND_NETS:
- VSS

FP_SIZING: absolute
DIE_AREA: 
  - 0 
  - 0 
  - 120
  - 28

PL_TARGET_DENSITY_PCT: 80
GRT_ALLOW_CONGESTION: true

PDN_MULTILAYER: false
RT_MAX_LAYER: Metal4

TOP_MARGIN_MULT:    1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT:   1
RIGHT_MARGIN_MULT:  1

IO_PIN_MIN_DISTANCE_IN_TRACKS: true
FP_IO_MIN_DISTANCE: 1

FP_IO_VLAYER: Metal4
FP_IO_HLAYER: Metal4